"""
Agent-Based Code Execution using Amazon AgentCore Bedrock Code Interpreter

This script demonstrates how to create an AI agent that validates answers through code execution 
using Python. We use Amazon Bedrock AgentCore Code Interpreter to run code that is generated by the LLM.
"""

from bedrock_agentcore.tools.code_interpreter_client import code_session
from langchain_core.tools import tool
from langchain_aws import ChatBedrockConverse
from langchain.agents import create_agent
import json

# System Prompt Definition
SYSTEM_PROMPT = """You are a helpful AI assistant that validates all answers through code execution.

VALIDATION PRINCIPLES:
1. When making claims about code, algorithms, or calculations - write code to verify them
2. Use execute_python to test mathematical calculations, algorithms, and logic
3. Create test scripts to validate your understanding before giving answers
4. Always show your work with actual code execution
5. If uncertain, explicitly state limitations and validate what you can

APPROACH:
- If asked about a programming concept, implement it in code to demonstrate
- If asked for calculations, compute them programmatically AND show the code
- If implementing algorithms, include test cases to prove correctness
- Document your validation process for transparency
- The sandbox maintains state between executions, so you can refer to previous results

TOOL AVAILABLE:
- execute_python: Run Python code and see output

RESPONSE FORMAT: The execute_python tool returns a JSON response with:
- sessionId: The sandbox session ID
- id: Request ID
- isError: Boolean indicating if there was an error
- content: Array of content objects with type and text/data
- structuredContent: For code execution, includes stdout, stderr, exitCode, executionTime"""

# Code Execution Tool Definition
@tool
def execute_python(code: str, description: str = "") -> str:
    """Execute Python code in the sandbox."""
    
    if description:
        code = f"# {description}\n{code}"
    
    print(f"\nGenerated Code: {code}")
    
    with code_session("us-east-1") as code_client:
        response = code_client.invoke("executeCode", {
            "code": code,
            "language": "python",
            "clearContext": False
        })
    
    for event in response["stream"]:
        return json.dumps(event["result"])

def main():
    llm = ChatBedrockConverse(
        model_id="amazon.nova-pro-v1:0",
        region_name="us-east-1"
    )
    
    tools = [execute_python]
    
    agent = create_agent(
        llm,
        tools=tools,
        system_prompt=SYSTEM_PROMPT
    )
    
    query = "Can all the planets in the solar system fit between the earth and moon?"
    # query = "How long would it take light to travel from the Sun to each planet?"
    
    # Agent Invocation and Response Processing
    print(f"\nQuery: {query}\n")
    response = agent.invoke({"messages": [{"role": "user", "content": query}]})
    
    # Display the final response
    print("\n" + "="*80)
    print("FINAL RESPONSE:")
    print("="*80)
    
    # Extract the final message from the response
    if "messages" in response:
        final_message = response["messages"][-1]
        if hasattr(final_message, 'content'):
            print(final_message.content)
        else:
            print(final_message)
    else:
        print(response)

if __name__ == "__main__":
    main()
